In [1]:
import sys # for automation and parallelization: set manual to false when run by a launcher
manual, scenario = (True, 'base') if 'ipykernel' in sys.argv[0] else (False, sys.argv[1])
import sys


from quetzal.model import stepmodel
import os
import pandas as pd
if manual:
    %matplotlib inline

PyTables is not installed. No support for HDF output.
SQLalchemy is not installed. No support for SQL output.

In [2]:
import sys # for automation and parallelization: set manual to false when run by a launcher
manual, scenario = (True, 'base') if 'ipykernel' in sys.argv[0] else (False, sys.argv[1])

In [3]:
training_folder = '../'

In [8]:
sm = stepmodel.read_json('C:/Users/BSE/Documents/MaxVonMylius/OR-MSM/quetzal_paris/model/network')

In [9]:
sm.road_links.head()

,a,b,length,geometry,highway,maxspeed
index,,,,,,
1,125730,268675130,8.707,"LINESTRING (2.41073 48.86352, 2.41083 48.86348)",residential,30
2,125730,21112878,142.342,"LINESTRING (2.41073 48.86352, 2.41012 48.86473)",residential,30
3,125730,244455548,105.925,"LINESTRING (2.41073 48.86352, 2.41092 48.86258)",residential,30
4,125730,1089076182,128.653,"LINESTRING (2.41073 48.86352, 2.40899 48.86337)",residential,30
5,125742,60912980,131.074,"LINESTRING (2.40137 48.85185, 2.40080 48.85297)",residential,30

In [ ]:

# sm.road_links['time']=(sm.road_links['length'])/(sm.road_links['maxspeed'].astype(float))

In [ ]:
# sm.road_links.head()

,a,b,length,geometry,highway,maxspeed,time
index,,,,,,,
1,125730,268675130,8.707,"LINESTRING (2.41073 48.86352, 2.41083 48.86348)",residential,30,0.290233
2,125730,21112878,142.342,"LINESTRING (2.41073 48.86352, 2.41012 48.86473)",residential,30,4.744733
3,125730,244455548,105.925,"LINESTRING (2.41073 48.86352, 2.41092 48.86258)",residential,30,3.530833
4,125730,1089076182,128.653,"LINESTRING (2.41073 48.86352, 2.40899 48.86337)",residential,30,4.288433
5,125742,60912980,131.074,"LINESTRING (2.40137 48.85185, 2.40080 48.85297)",residential,30,4.369133

In [ ]:
# sm.road_links.loc[sm.road_links['maxspeed'].apply(lambda s: s=='walk'),'maxspeed']=8

,a,b,length,geometry
index,,,,
1,125730,268675130,8.707,"LINESTRING (2.41073 48.86352, 2.41083 48.86348)"
2,125730,21112878,142.342,"LINESTRING (2.41073 48.86352, 2.41012 48.86473)"

In [13]:
sm.road_links.loc[sm.road_links['maxspeed'].apply(lambda s: s=='walk'),'maxspeed']=8
sm.road_links.loc[sm.road_links['maxspeed'].apply(lambda s: isinstance(s,list)),'maxspeed']=50
sm.road_links['time']=(sm.road_links['length'])/(0.6 * sm.road_links['maxspeed'].astype(float))

In [14]:
sm.road_links.head(2)

,a,b,length,geometry,highway,maxspeed,time
index,,,,,,,
1,125730,268675130,8.707,"LINESTRING (2.41073 48.86352, 2.41083 48.86348)",residential,30,0.483722
2,125730,21112878,142.342,"LINESTRING (2.41073 48.86352, 2.41012 48.86473)",residential,30,7.907889